name: CI

on:
  push: # Run on push to master branch
    branches: 
      - master
  pull_request: # Run on pull request to master branch
    branches:
      - master

jobs:
  build: # Job name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout the code
      - name: Run a one-line script
        run: echo Hello world!
